#pragma once

#define LT_TNAV LT(_NAV,KC_TAB)
#define MT_CTES MT(MOD_LCTL,KC_ESC)
#define MT_GUBS MT(MOD_LGUI,KC_BSPC)
#define MT_ALDL MT(MOD_LALT,KC_DEL)
#define MT_ALEN MT(MOD_LALT|MOD_RALT,KC_ENT)
